### ISSUE TITLE
iOS integration very hard for continuous integration on pipelines, pls add Pods support

### ISSUE THREAD

**Issue by expcapitaldev** [iovation/deviceprint-SDK-iOS#20]
for example part with installation https://github.com/iovation/deviceprint-SDK-iOS#installation

**Comment by ashley-campbell-iovation** [comment]
Hello!

Due to the nature of our library, particularly around the fact that the library is obfuscated, it was determined by our engineering team that CocoaPods is not the right fit for us. Pods intended use is for Open Sourced libraries which is not a classification we fall under. 

We do offer Carthage as an alternative method of distribution management:  https://iovation.github.io/deviceprint-SDK-iOS/

Thanks!
Ashley

**Comment by ashley-campbell-iovation** [comment]
I also wanted to suggest that our XCFramework bundle could also be a good integration option for a more streamline process.

Ashley
